# Documentation: https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
  - linters
  - unit-tests

check:
  stage: linters
  image: python:3.6
  allow_failure: yes
  before_script:
    - pip install poetry
    - poetry install -n
    - poetry run make protos
  script:
    - poetry run make check

unit-tests:
  stage: unit-tests
  image: python:3.6
  before_script:
    - apt update
    - apt install -y graphviz
    - apt install -y librocksdb-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev
    - pip install poetry
    - poetry install -n -E rocksdb
    - poetry run make protos
  script:
    - poetry run make tests
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
